export const ACTIONS = {
  SET_INITIAL_DATA: "SET_INITIAL_DATA",
  ADD_STUDENT: "ADD_STUDENT",
  REMOVE_FIRST: "REMOVE_FIRST",
  UPDATE_ABSENT: "UPDATE_ABSENT",
  SET_FILTER: "SET_FILTER",
} as const;

